### ISSUE TITLE
Did you stop supporting Theia-cv?

### ISSUE THREAD

**Issue by curtdissel** [ghokun/ghokun#1]
Hullo Ghokun, sorry to use issues like this, but i didn't know how to contact you.

I was curious if you know that the Dockerfile in:
https://github.com/ghokun/theia-cv

No longer builds. I just wanted to make sure you were aware of that.

I was working on a variation with python-opencv support and noticed that the docker file doesn't build.

**Comment by ghokun** [comment]
Hi, I migrated most of my dev environment to code-server or vscode devcontainers.

You can find them here: https://github.com/works-on-my-machine

**Comment by curtdissel** [comment]
I saw that. But I didn't see any theia repos in your works on my machine repo. Are there plans on working with Theia anymore or will it only be VSCode for you?

**Comment by ghokun** [comment]
I liked code-server better than Theia so I switched to it. I don't have a plan to work with Theia.

Here is the one that replaced theia-cv:
https://github.com/works-on-my-machine/opencv-code-server

But I can help you if you have a repo that fails to build etc..

**Comment by curtdissel** [comment]
I was looking at Theia because I wanted to make interactive coding environments with lessons in computer vision or ML.

The thought was when a user clicks a lesson, the appropriate docker container is loaded with everything needed for the lesson.

I will play around with opencv-code-server to see if it can provide an experience of just running inside a docker container.

**Comment by curtdissel** [comment]
As an update, the error I get when building opencv-code-server is the same as on Theia.

#10 6.374 Fetched 38.0 MB in 6s (6,490 kB/s)
#10 6.374 Reading package lists...
#10 7.524 Reading package lists...
#10 8.669 Building dependency tree...
#10 8.856 Reading state information...
#10 8.990 E: Unable to locate package clang-tools-12
#10 8.990 E: Unable to locate package clangd-12
#10 8.990 E: Unable to locate package clang-tidy-12

I wonder if clang has had changes over the year. Neither repo can find it when building from scratch.

I performed the docker build on my Mac as well as my Ubuntu work station and get the same exact error.

**Comment by ghokun** [comment]
> I was working on a variation with python-opencv support and noticed that the docker file doesn't build.

If you want python you dont need clang. Perhaps a simple docker mod by linuxserver community works for you:

```bash
docker run -d \
  --name=code-server \
  -e DOCKER_MODS=linuxserver/mods:code-server-python3 \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Europe/London \
  -e PASSWORD=password `#optional` \
  -e HASHED_PASSWORD= `#optional` \
  -e SUDO_PASSWORD=password `#optional` \
  -e SUDO_PASSWORD_HASH= `#optional` \
  -e PROXY_DOMAIN=code-server.my.domain `#optional` \
  -p 8443:8443 \
  -v /path/to/appdata/config:/config \
  --restart unless-stopped \
  ghcr.io/linuxserver/code-server
```

More info here: https://mods.linuxserver.io/
